Repository GSA-TTS/FAC, pull requests merged in 2023-09, with the labels that each got.

#2008 2023-09-01 | MAIN --> PROD | DEV (6464825) --> STAGING
  backend/api/views.py
  backend/audit/migrations/0038_submissionevent.py
  backend/audit/models.py
  backend/audit/test_views.py
  backend/audit/viewlib/upload_report_view.py
  backend/audit/views.py
  backend/data_fixtures/audit/excel_schema_test_files/federal-awards-audit-findings-pass-01.json
  backend/data_fixtures/audit/test_data_entries/federal-awards-audit-findings-entries.json
  backend/docker-compose.yml
  backend/report_submission/test_views.py
  backend/report_submission/views.py
  backend/run.sh
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/source/sections/FederalAwardsAuditFindings.schema.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.validation.libsonnet
  terraform/shared/modules/env/postgrest.tf
Labels: autogenerated, automerge

#1993 Ez/additional eins e2e
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/fixtures/test_workbooks/additional-eins-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/additional-ueis-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/audit-findings-text-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/corrective-action-plan-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-audit-findings-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/notes-to-sefa-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/secondary-auditors-workbook.xlsx
  backend/cypress/support/general-info.js
  backend/cypress/support/workbook-uploads.js
Labels: front end

#2014 2023-09-02 | MAIN --> PROD | DEV (6138868) --> STAGING
  .github/workflows/deploy-application.yml
  backend/.profile
  backend/apt.yml
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/fixtures/test_workbooks/additional-eins-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/additional-ueis-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/audit-findings-text-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/corrective-action-plan-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-audit-findings-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/notes-to-sefa-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/secondary-auditors-workbook.xlsx
  backend/cypress/support/general-info.js
  backend/cypress/support/workbook-uploads.js
  backend/load_data.sh
  backend/manifests/manifest-fac.yml
  terraform/shared/modules/env/https-proxy.tf
  terraform/shared/modules/env/postgrest.tf
Labels: autogenerated, automerge

#2025 2023-09-06 | MAIN --> PROD | DEV (e84c006) --> STAGING
  backend/audit/models.py
  backend/audit/test_views.py
Labels: autogenerated, automerge

#2027 2023-09-06 | MAIN --> PROD | DEV (59d3a4e) --> STAGING
  .github/workflows/deploy-application.yml
  .github/workflows/end-to-end-test.yml
  .github/workflows/testing-from-build.yml
  .github/workflows/testing-from-ghcr.yml
  backend/config/settings.py
  backend/docker-compose-web.yml
  backend/docker-compose.yml
  backend/load_data.sh
  docs/development.md
Labels: autogenerated, automerge

#2043 2023-09-07 | MAIN --> PROD | DEV (015f5e1) --> STAGING
  .github/pull_request_template.md
  .github/workflows/add-bpmn-renders.yml
  .github/workflows/build-docker-container.yml
  .github/workflows/create-pull-request-to-staging.yml
  .github/workflows/create-release.yml
  .github/workflows/deploy-application.yml
  .github/workflows/end-to-end-test.yml
  .github/workflows/linting.yml
  .github/workflows/pull-containers-and-push-to-ghcr.yml
  .github/workflows/regression-tests.yml
  .github/workflows/terraform-apply-env.yml
  .github/workflows/terraform-lint.yml
  .github/workflows/terraform-plan-env.yml
  .github/workflows/testing-from-build.yml
  .github/workflows/testing-from-ghcr.yml
  .github/workflows/trivy.yml
  .github/workflows/zap-scan.yml
  backend/pa11y-run.js
  backend/package-lock.json
  backend/package.json
Labels: autogenerated, automerge

#2054 2023-09-08 | MAIN --> PROD | DEV (fd5fb98) --> STAGING
  .github/workflows/create-release.yml
  SECURITY.md
  backend/api/test_views.py
  backend/audit/etl.py
  backend/audit/fixtures/single_audit_checklist.py
  backend/audit/test_cog_over.py
  backend/audit/test_etl.py
  backend/config/settings.py
  backend/dissemination/models.py
  backend/report_submission/forms.py
  backend/report_submission/templates/report_submission/gen-form.html
  backend/report_submission/test_views.py
  backend/report_submission/views.py
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/base/States.json
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
  backend/static/js/sf-sac.js
Labels: autogenerated, automerge

#2072 Ez/2047 submit final submission cy
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/support/general-info.js
Labels: MUST

#2089 2023-09-13 | MAIN --> PROD | DEV (62f5f6d) --> STAGING
  backend/docker-compose.yml
  docs/development.md
Labels: autogenerated, automerge

#2094 2023-09-13 | MAIN --> PROD | DEV (b2cb3d4) --> STAGING
  .github/workflows/build-docker-container.yml
  .github/workflows/pull-containers-and-push-to-ghcr.yml
Labels: autogenerated, automerge

#2097 2023-09-13 | MAIN --> PROD | DEV (43e0039) --> STAGING
  backend/cypress/fixtures/test_workbooks/secondary-auditors-workbook.xlsx
  backend/schemas/.gitignore
  backend/schemas/output/excel/json/additional-eins-workbook.json
  backend/schemas/output/excel/json/additional-ueis-workbook.json
  backend/schemas/output/excel/json/audit-findings-text-workbook.json
  backend/schemas/output/excel/json/corrective-action-plan-workbook.json
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/excel/json/notes-to-sefa-workbook.json
  backend/schemas/output/excel/json/secondary-auditors-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/source/excel/templates/secondary-auditors-workbook.jsonnet
  terraform/shared/modules/env/https-proxy.tf
Labels: autogenerated, automerge

#2084 2062 add additional ein to dissemination
  backend/audit/intake_to_dissemination.py
  backend/audit/test_intake_to_dissemination.py
  backend/audit/utils.py
  backend/dissemination/migrations/0002_additionalein.py
  backend/dissemination/models.py
Labels: eng

#2111 2023-09-14 | MAIN --> PROD | DEV (eeb31ae) --> STAGING
  backend/audit/intake_to_dissemination.py
  backend/audit/test_intake_to_dissemination.py
  backend/audit/utils.py
  backend/dissemination/migrations/0002_additionalein.py
  backend/dissemination/models.py
Labels: autogenerated, automerge

#2137 2023-09-15 | MAIN --> PROD | DEV (2505c3a) --> STAGING
  .github/ISSUE_TEMPLATE/helpdesk-issue.yml
  backend/cypress/e2e/full-submission.cy.js
Labels: autogenerated, automerge

#2164 2023-09-19 | MAIN --> PROD | DEV (8cd0fcb) --> STAGING
  backend/dev-requirements.txt
  backend/requirements/dev-requirements.in
  backend/schemas/.gitignore
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/scripts/parse.py
  backend/schemas/scripts/render.py
  backend/schemas/scripts/xlrows.py
  backend/schemas/source/excel/libs/Sheets.libsonnet
Labels: autogenerated, automerge

#2193 2023-09-21 | MAIN --> PROD | DEV (d7c3dbf) --> STAGING
  .github/workflows/deploy-application.yml
  .github/workflows/terraform-apply-env.yml
  backend/config/context_processors.py
  backend/config/settings.py
  backend/templates/includes/header.html
  backend/templates/includes/nav_primary.html
Labels: autogenerated, automerge

#2207 2023-09-21 | MAIN --> PROD | DEV (fd3a592) --> STAGING
  .github/workflows/linting.yml
  .github/workflows/terraform-apply-env.yml
  backend/Makefile
  backend/audit/intake_to_dissemination.py
  backend/audit/test_intake_to_dissemination.py
  backend/static/js/check-ueid.js
  docs/deploying.md
  terraform/meta/README.md
  terraform/meta/meta.tf
Labels: autogenerated, automerge

#2223 2023-09-22 | MAIN --> PROD | DEV (dee5610) --> STAGING
  backend/static/js/check-ueid.js
  backend/support/management/commands/seed_cog_baseline.py
Labels: autogenerated, automerge

#2233 2023-09-23 | MAIN --> PROD | DEV (a9cc1a6) --> STAGING
  .github/workflows/regression-tests.yml
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/support/dissemination-table.js
Labels: autogenerated, automerge

#2262 2023-09-27 | MAIN --> PROD | DEV (83eeca2) --> STAGING
  backend/.stylelintignore
  backend/.stylelintrc.json
  backend/package-lock.json
  backend/package.json
  backend/static/scss/main.scss
Labels: autogenerated, automerge

#2297 2023-09-29 | MAIN --> PROD | DEV (7c79e72) --> STAGING
  backend/Apple_M1_Dockerfile
  backend/report_submission/views.py
  backend/support/management/commands/collect_metrics.py
  backend/support/management/commands/purge_data.py
Labels: autogenerated, automerge

#2321 2023-09-29 | MAIN --> PROD | DEV (f639e0d) --> STAGING
  backend/audit/admin.py
  backend/cypress/support/general-info.js
  backend/report_submission/templates/report_submission/step-2.html
  backend/report_submission/test_views.py
  backend/report_submission/views.py
  backend/users/auth.py
  backend/users/test_auth.py
Labels: autogenerated, automerge
