Repository GSA-TTS/FAC, pull requests merged in 2023-12, with the labels that each got.

#2908 2023-12-01 | MAIN --> PROD | DEV (de7c759) --> STAGING
  backend/audit/admin.py
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/additional-eins-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/additional-ueis-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/audit-findings-text-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/corrective-action-plan-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/federal-awards-audit-findings-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/federal-awards-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/notes-to-sefa-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/177310-22/secondary-auditors-workbook-177310.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/additional-eins-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/additional-ueis-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/audit-findings-text-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/corrective-action-plan-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/federal-awards-audit-findings-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/federal-awards-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/notes-to-sefa-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/secondary-auditors-workbook-180818.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/180818-22/test-array-180818.json
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/additional-eins-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/additional-ueis-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/audit-findings-text-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/corrective-action-plan-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/federal-awards-audit-findings-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/federal-awards-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/notes-to-sefa-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/secondary-auditors-workbook-217653.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/217653-22/test-array-217653.json
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/additional-eins-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/additional-ueis-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/audit-findings-text-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/corrective-action-plan-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/federal-awards-audit-findings-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/federal-awards-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/notes-to-sefa-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/secondary-auditors-workbook-251020.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/251020-22/test-array-251020.json
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/additional-eins-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/additional-ueis-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/audit-findings-text-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/corrective-action-plan-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/federal-awards-audit-findings-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/federal-awards-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/notes-to-sefa-workbook-69688.xlsx
  backend/census_historical_migration/fixtures/workbooks/should_pass/69688-22/secondary-auditors-workbook-69688.xlsx
  backend/census_historical_migration/test_core_xforms.py
  backend/census_historical_migration/workbooklib/notes_to_sefa.py
Labels: autogenerated, automerge

#2905 2895: New cmd for paginated census migration
  backend/census_historical_migration/README.md
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/run_paginated_migration.py
Labels: census

#2906 2901 update logic in general information to use census models
  backend/census_historical_migration/admin.py
  backend/census_historical_migration/sac_general_lib/audit_information.py
  backend/census_historical_migration/sac_general_lib/auditee_certification.py
  backend/census_historical_migration/sac_general_lib/auditor_certification.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/sac_general_lib/report_id_generator.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/sac_general_lib/utils.py
  backend/census_historical_migration/test_excel_creation.py
  backend/census_historical_migration/workbooklib/additional_eins.py
  backend/census_historical_migration/workbooklib/additional_ueis.py
  backend/census_historical_migration/workbooklib/census_models/census.py
  backend/census_historical_migration/workbooklib/corrective_action_plan.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
  backend/census_historical_migration/workbooklib/excel_creation_utils.py
  backend/census_historical_migration/workbooklib/federal_awards.py
  backend/census_historical_migration/workbooklib/findings.py
  backend/census_historical_migration/workbooklib/findings_text.py
  backend/census_historical_migration/workbooklib/secondary_auditors.py
  backend/census_historical_migration/workbooklib/workbook_builder.py
  backend/census_historical_migration/workbooklib/workbook_builder_loader.py
  backend/census_historical_migration/workbooklib/workbook_section_handlers.py
Labels: census

#2914 2023-12-02 | MAIN --> PROD | DEV (7ad3cbb) --> STAGING
  backend/census_historical_migration/README.md
  backend/census_historical_migration/admin.py
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/run_paginated_migration.py
  backend/census_historical_migration/sac_general_lib/audit_information.py
  backend/census_historical_migration/sac_general_lib/auditee_certification.py
  backend/census_historical_migration/sac_general_lib/auditor_certification.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/sac_general_lib/report_id_generator.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/sac_general_lib/utils.py
  backend/census_historical_migration/test_excel_creation.py
  backend/census_historical_migration/workbooklib/additional_eins.py
  backend/census_historical_migration/workbooklib/additional_ueis.py
  backend/census_historical_migration/workbooklib/census_models/census.py
  backend/census_historical_migration/workbooklib/corrective_action_plan.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
  backend/census_historical_migration/workbooklib/excel_creation_utils.py
  backend/census_historical_migration/workbooklib/federal_awards.py
  backend/census_historical_migration/workbooklib/findings.py
  backend/census_historical_migration/workbooklib/findings_text.py
  backend/census_historical_migration/workbooklib/secondary_auditors.py
  backend/census_historical_migration/workbooklib/workbook_builder.py
  backend/census_historical_migration/workbooklib/workbook_builder_loader.py
  backend/census_historical_migration/workbooklib/workbook_section_handlers.py
Labels: autogenerated, automerge

#2943 2023-12-07 | MAIN --> PROD | DEV (4ebd64f) --> STAGING
  backend/report_submission/test_views.py
  backend/report_submission/views.py
  backend/static/js/check-ueid.js
  docs/deploying.md
Labels: autogenerated, automerge

#2944 2675: Improve census migration exception handling
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
Labels: census

#2976 2023-12-12 | MAIN --> PROD | DEV (03c5997) --> STAGING
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/historic_data_migrator.py
  docs/django-admin-operations.md
Labels: autogenerated, automerge

#2995 2023-12-13 | MAIN --> PROD | DEV (6c729a6) --> STAGING
  backend/audit/admin.py
Labels: autogenerated, automerge

#3015 2023-12-16 | MAIN --> PROD | DEV (e8aa48e) --> STAGING
  backend/audit/cross_validation/naming.py
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/intake_to_dissemination.py
  backend/audit/templates/audit/auditee-certification-step-1.html
  backend/audit/templates/audit/auditor-certification-step-1.html
  backend/audit/templates/audit/manage-submission.html
  backend/audit/test_submission_progress_view.py
  backend/audit/urls.py
  backend/audit/views/__init__.py
  backend/audit/views/pre_dissemination_download_view.py
  backend/audit/views/upload_report_view.py
  backend/census_historical_migration/management/commands/csv_to_postgres.py
  backend/census_historical_migration/migrations/0003_remove_migrationerrordetail_error_stack_and_more.py
  backend/census_historical_migration/models.py
  backend/dissemination/file_downloads.py
  backend/dissemination/forms.py
  backend/dissemination/management/commands/end_to_end_test_data_generator.py
  backend/dissemination/search.py
  backend/dissemination/summary_reports.py
  backend/dissemination/templates/search-table-header.html
  backend/dissemination/templates/search.html
  backend/dissemination/templates/summary.html
  backend/dissemination/test_search.py
  backend/dissemination/test_summary_reports.py
  backend/dissemination/test_views.py
  backend/dissemination/urls.py
  backend/dissemination/views.py
  backend/dissemination/workbooklib/end_to_end_core.py
  backend/dissemination/workbooklib/sac_creation.py
  backend/dissemination/workbooklib/workbook_creation.py
  backend/report_submission/templates/report_submission/step-2.html
  backend/static/js/search-results-pagination.js
  backend/static/js/search-results.js
Labels: autogenerated, automerge

#3024 2023-12-18 | MAIN --> PROD | DEV (0fc5be6) --> STAGING
  .github/workflows/deploy-application.yml
Labels: autogenerated, automerge

#3034 2023-12-19 | MAIN --> PROD | DEV (8e3281d) --> STAGING
  backend/audit/admin.py
  backend/audit/views/__init__.py
  backend/audit/views/audit_info_form_view.py
  backend/audit/views/views.py
  backend/users/admin.py
Labels: autogenerated, automerge

#3031 Sk/migration sac transition
  backend/census_historical_migration/workbooklib/end_to_end_core.py
Labels: census

#2961 Send CF Logs to New Relic and S3
  .github/workflows/deploy-application.yml
  .github/workflows/terraform-apply-env.yml
  .github/workflows/terraform-plan-env.yml
  backend/manifests/manifest-fac.yml
  terraform/shared/modules/cg-logshipper/cg-logshipper.tf
  terraform/shared/modules/cg-logshipper/fluentbit_config/fluentbit.conf
  terraform/shared/modules/cg-logshipper/outputs.tf
  terraform/shared/modules/cg-logshipper/prepare-logshipper.sh
  terraform/shared/modules/cg-logshipper/providers.tf
  terraform/shared/modules/cg-logshipper/readme.md
  terraform/shared/modules/cg-logshipper/variables.tf
  terraform/shared/modules/env/logshipper.tf
  terraform/shared/modules/env/newrelic.tf
  terraform/shared/modules/https-proxy/https-proxy.tf
  terraform/shared/modules/https-proxy/outputs.tf
Labels: infrastructure

#3049 3023 implement transformation for invalid alns
  backend/audit/intakelib/checks/check_additional_award_identification_present.py
  backend/audit/intakelib/checks/check_aln_three_digit_extension_pattern.py
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/csv_to_postgres.py
  backend/census_historical_migration/management/commands/historic_data_migrator.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/test_federal_awards_xforms.py
  backend/census_historical_migration/test_workbooks_should_pass.py
  backend/census_historical_migration/transforms/xform_remove_hyphen_and_pad_zip.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
  backend/census_historical_migration/workbooklib/federal_awards.py
  backend/census_historical_migration/workbooklib/post_upload_utils.py
  backend/config/settings.py
  backend/schemas/source/base/Base.libsonnet
Labels: census

#3073 2023-12-22 | MAIN --> PROD | DEV (67b29fb) --> STAGING
  backend/audit/admin.py
  backend/audit/fixtures/workbooks/should_pass/cluster_names/tests-cluster-names.xlsx
  backend/audit/intakelib/checks/check_additional_award_identification_present.py
  backend/audit/intakelib/checks/check_aln_three_digit_extension_pattern.py
  backend/audit/intakelib/checks/check_cluster_names.py
  backend/audit/models/access.py
  backend/audit/test_models.py
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/csv_to_postgres.py
  backend/census_historical_migration/management/commands/historic_data_migrator.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/test_federal_awards_xforms.py
  backend/census_historical_migration/test_workbooks_should_pass.py
  backend/census_historical_migration/transforms/xform_remove_hyphen_and_pad_zip.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
  backend/census_historical_migration/workbooklib/federal_awards.py
  backend/census_historical_migration/workbooklib/post_upload_utils.py
  backend/config/settings.py
  backend/schemas/source/base/Base.libsonnet
  terraform/shared/modules/cg-logshipper/prepare-logshipper.sh
Labels: autogenerated, automerge

#3075 2023-12-22 | MAIN --> PROD | DEV (b1e0a77) --> STAGING
  .github/ISSUE_TEMPLATE/api-access-template.yaml
  .github/ISSUE_TEMPLATE/cross-validation.md
  .github/ISSUE_TEMPLATE/design-issue-template.md
  .github/ISSUE_TEMPLATE/epic-template.md
  .github/ISSUE_TEMPLATE/snip-acceptance-criteria.md
  .github/ISSUE_TEMPLATE/snip-at-a-glance.md
  .github/ISSUE_TEMPLATE/snip-background.md
  .github/ISSUE_TEMPLATE/snip-content-signoff.md
  .github/ISSUE_TEMPLATE/snip-scenario.md
  .github/ISSUE_TEMPLATE/snip-security-considerations.md
  .github/ISSUE_TEMPLATE/snip-shepherd.md
  .github/ISSUE_TEMPLATE/snip-story-process.md
  backend/audit/test_manage_submission_access_view.py
  backend/audit/views/manage_submission.py
  backend/audit/views/manage_submission_access.py
  backend/config/settings.py
  backend/dissemination/search.py
  backend/dissemination/summary_reports.py
  backend/dissemination/templates/search-alert-info.html
  backend/dissemination/templates/search.html
  backend/dissemination/test_views.py
  backend/dissemination/urls.py
  backend/dissemination/views.py
Labels: autogenerated, automerge

#3080 2023-12-23 | MAIN --> PROD | DEV (a660153) --> STAGING
  backend/audit/fixtures/workbooks/should_pass/cluster_names/tests-cluster-names.xlsx
  backend/audit/intakelib/checks/check_cluster_names.py
  backend/audit/intakelib/checks/check_cluster_total.py
  backend/audit/intakelib/checks/check_other_cluster_names.py
  backend/audit/intakelib/checks/check_state_cluster_names.py
  backend/dissemination/views.py
Labels: autogenerated, automerge

#3083 2023-12-26 | MAIN --> PROD | DEV (6e549dd) --> STAGING
  backend/audit/fixtures/workbooks/should_fail/federal-awards-audit-findings/has_bad_award_references.xlsx
  backend/audit/fixtures/workbooks/should_pass/award_references/has-lowercase-award-reference.xlsx
  backend/audit/intakelib/checks/check_finding_award_references_pattern.py
  backend/audit/intakelib/checks/runners.py
  backend/audit/intakelib/common/error_messages.py
  backend/audit/intakelib/transforms/runners.py
  backend/audit/intakelib/transforms/xform_reformat_award_references.py
Labels: autogenerated, automerge

#3086 2023-12-26 | MAIN --> PROD | DEV (84b08a1) --> STAGING
  .github/workflows/historic-data-migrator.yml
  backend/census_historical_migration/api_test_helpers.py
  backend/census_historical_migration/end_to_end_core.py
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/csv_to_postgres.py
  backend/census_historical_migration/management/commands/historic_data_migrator.py
  backend/census_historical_migration/sac_general_lib/audit_information.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/test_federal_awards_xforms.py
  backend/census_historical_migration/workbooklib/additional_eins.py
  backend/census_historical_migration/workbooklib/additional_ueis.py
  backend/census_historical_migration/workbooklib/corrective_action_plan.py
  backend/census_historical_migration/workbooklib/excel_creation_utils.py
  backend/census_historical_migration/workbooklib/federal_awards.py
  backend/census_historical_migration/workbooklib/findings.py
  backend/census_historical_migration/workbooklib/findings_text.py
  backend/census_historical_migration/workbooklib/notes_to_sefa.py
  backend/census_historical_migration/workbooklib/post_upload_utils.py
  backend/census_historical_migration/workbooklib/secondary_auditors.py
  backend/census_historical_migration/workbooklib/workbook_builder_loader.py
  backend/config/settings.py
Labels: autogenerated, automerge

#3088 2023-12-27 | MAIN --> PROD | DEV (3635277) --> STAGING
  backend/audit/fixtures/workbooks/should_fail/federal-awards/has-bad-aln-prefixes.xlsx
  backend/audit/fixtures/workbooks/should_pass/aln_read_as_decimal_values/has-aln-prefix-returned-as-decimal-numbers.xlsx
  backend/audit/intakelib/checks/check_aln_prefix_pattern.py
  backend/audit/intakelib/checks/check_finding_award_references_pattern.py
  backend/audit/intakelib/checks/runners.py
  backend/audit/intakelib/common/error_messages.py
  backend/audit/intakelib/transforms/runners.py
  backend/audit/intakelib/transforms/xform_reformat_agency_prefix.py
  backend/audit/intakelib/transforms/xform_reformat_award_references.py
  backend/schemas/source/base/Base.libsonnet
  backend/static/js/globals.js
Labels: autogenerated, automerge

#3091 2023-12-27 | MAIN --> PROD | DEV (d9d7a63) --> STAGING
  backend/config/settings.py
  backend/manifests/vars/vars-production.yml
Labels: autogenerated, automerge

#3082 Census migration: Making `result` a module var
  backend/census_historical_migration/historic_data_loader.py
  backend/census_historical_migration/management/commands/historic_data_migrator.py
  backend/census_historical_migration/migration_result.py
  backend/census_historical_migration/sac_general_lib/audit_information.py
  backend/census_historical_migration/sac_general_lib/auditee_certification.py
  backend/census_historical_migration/sac_general_lib/auditor_certification.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/sac_general_lib/sac_creator.py
  backend/census_historical_migration/sac_general_lib/utils.py
  backend/census_historical_migration/workbooklib/end_to_end_core.py
  backend/census_historical_migration/workbooklib/federal_awards.py
Labels: census

#3104 2023-12-29 | MAIN --> PROD | DEV (0e65d49) --> STAGING
  .github/workflows/create-release.yml
  backend/Dockerfile
  backend/audit/cross_validation/errors.py
  backend/audit/fixtures/workbooks/should_fail/audit-findings/has-bad-yes-or-no-inputs.xlsx
  backend/audit/fixtures/workbooks/should_fail/audit-findings/has_bad_award_references.xlsx
  backend/audit/fixtures/workbooks/should_fail/audit-findings/has_bad_prior_references.xlsx
  backend/audit/fixtures/workbooks/should_fail/audit-findings/missing-required-fields.xlsx
  backend/audit/fixtures/workbooks/should_fail/federal-awards/has-empty-loan-balance-but-balance-is-required.xlsx
  backend/audit/fixtures/workbooks/should_pass/cluster_names/tests-cluster-names.xlsx
  backend/audit/fixtures/workbooks/should_pass/federal_awards/federal-awards-has-aln-prefix-returned-as-decimal-numbers.xlsx
  backend/audit/fixtures/workbooks/should_pass/federal_awards/federal-awards-has-loan-guarantee-and-zero-loan-balance.xlsx
  backend/audit/fixtures/workbooks/should_pass/federal_awards/federal-awards-has-negative-loan-balance.xlsx
  backend/audit/fixtures/workbooks/should_pass/federal_awards/federal-awards-tests-cluster-names.xlsx
  backend/audit/fixtures/workbooks/should_pass/federal_awards_audit_findings/audit-findings-has-lowercase-award-reference.xlsx
  backend/audit/intakelib/checks/check_loan_balance_entries.py
  backend/audit/intakelib/checks/check_loan_balance_present.py
  backend/audit/intakelib/checks/runners.py
  backend/audit/intakelib/common/__init__.py
  backend/audit/intakelib/common/util.py
  backend/audit/intakelib/transforms/runners.py
  backend/audit/intakelib/transforms/xform_federal_awards_cluster_name_to_uppercase.py
  backend/audit/intakelib/transforms/xform_loan_balance_need_to_be_integers.py
  backend/audit/test_intakelib_xforms.py
  backend/audit/test_workbooks_should_fail.py
  backend/audit/test_workbooks_should_pass.py
  backend/config/settings.py
  backend/dissemination/migrations/0007_remove_migrationchangerecord_census_data_and_more.py
  backend/dissemination/models.py
Labels: autogenerated, automerge

#3105 2023-12-30 | MAIN --> PROD | DEV (3469870) --> STAGING
  backend/Apple_M1_Dockerfile
  backend/Dockerfile
Labels: autogenerated, automerge
