Repository GSA-TTS/FAC, pull requests merged in 2023-08, with the labels that each got.

#1517 Upload Page Timeout
  backend/cypress/e2e/audit-findings-text.cy.js
  backend/cypress/e2e/audit-findings.cy.js
  backend/cypress/e2e/corrective-action-plan.cy.js
  backend/cypress/e2e/federal-awards.cy.js
  backend/cypress/e2e/workbook-uploads.cy.js
  backend/cypress/fixtures/fail-res.json
  backend/report_submission/templates/report_submission/upload-page.html
  backend/static/js/globals.js
  backend/static/js/upload-page.js
Labels: bug, front end

#1632 Audit Information Changes
  backend/.flake8
  backend/audit/forms.py
  backend/audit/get_agency_names.py
  backend/audit/migrations/0030_singleauditchecklist_audit_information.py
  backend/audit/models.py
  backend/audit/templates/audit/audit-info-form.html
  backend/audit/templates/audit/submission-progress.html
  backend/audit/templates/audit/upload-report.html
  backend/audit/test_schemas.py
  backend/audit/test_validators.py
  backend/audit/validators.py
  backend/audit/views.py
  backend/config/settings.py
  backend/cypress/e2e/audit-info-form.cy.js
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/report_submission/views.py
  backend/requirements.txt
  backend/requirements/requirements.in
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/sections/AdditionalUEIs.schema.json
  backend/schemas/output/sections/AuditInformation.schema.json
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/requirements.txt
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/base/FederalProgramNames.json
  backend/schemas/source/base/GAAP.libsonnet
  backend/schemas/source/sections/AuditInformation.schema.jsonnet
  backend/static/js/audit-info-form.js
Labels: front end, back end

#1820 2023-08-15 | MAIN --> PROD | DEV (c4d96b7) --> STAGING
  .github/ISSUE_TEMPLATE/offboarding.md
  .github/workflows/create-release.yml
  backend/audit/etl.py
  backend/audit/forms.py
  backend/audit/get_agency_names.py
  backend/audit/templates/audit/audit-info-form.html
  backend/audit/templates/audit/submission.html
  backend/audit/templates/audit/submission_checklist/created-by.html
  backend/audit/views.py
  backend/config/settings.py
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/support/cross-validation.js
  backend/schemas/output/sections/AuditInformation.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/base/GAAP.libsonnet
  backend/schemas/source/sections/AuditInformation.schema.jsonnet
  backend/static/js/audit-info-form.js
  terraform/preview/preview.tf
  terraform/preview/variables.tf
Labels: autogenerated, automerge

#1830 2023-08-16 | MAIN --> PROD | DEV (5f90a24) --> STAGING
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/additional_ueis.py
  backend/audit/cross_validation/audit_findings.py
  backend/audit/cross_validation/auditee_ueis_match.py
  backend/audit/cross_validation/errors.py
  backend/audit/cross_validation/number_of_findings.py
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/cross_validation/test_number_of_findings.py
  backend/audit/cross_validation/tribal_data_sharing_consent.py
  backend/audit/fixtures/excel.py
  backend/audit/models.py
  backend/audit/templates/audit/submission_checklist/submission-checklist.html
  backend/audit/test_views.py
  backend/audit/views.py
Labels: autogenerated, automerge

#1860 2023-08-17 | MAIN --> PROD | DEV (f1fb29b) --> STAGING
  .github/PULL_REQUEST_TEMPLATE/pr-review-template.md
  .github/workflows/regression-tests.yml
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/award_ref_and_references_uniqueness.py
  backend/audit/cross_validation/errors.py
  backend/audit/cross_validation/test_award_ref_and_references_uniqueness.py
  backend/audit/excel.py
  backend/audit/fixtures/excel.py
  backend/audit/migrations/0034_singleauditchecklist_additional_eins.py
  backend/audit/models.py
  backend/audit/test_excel.py
  backend/audit/test_validators.py
  backend/audit/test_views.py
  backend/audit/validators.py
  backend/audit/views.py
  backend/cypress/e2e/check-access.cy.js
  backend/cypress/e2e/createNewAudit.cy.js
  backend/cypress/fixtures/audit-findings-text-UPDATE.xlsx
  backend/cypress/fixtures/corrective-action-plan-UPDATE.xlsx
  backend/cypress/fixtures/federal-awards-UPDATE.xlsx
  backend/cypress/fixtures/federal-awards-audit-findings-UPDATE.xlsx
  backend/cypress/fixtures/federal-awards-expended-PASS.xlsx
  backend/cypress/fixtures/findings-text-UPDATE.xlsx
  backend/cypress/fixtures/findings-uniform-guidance-UPDATE.xlsx
  backend/cypress/fixtures/secondary-auditors-template.xlsx
  backend/cypress/support/check-access.js
  backend/cypress/support/workbook-uploads.js
  backend/data_fixtures/audit/excel_schema_test_files/additional-eins-pass-01.json
  backend/data_fixtures/audit/test_data_entries/additional-eins-entries.json
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/report_submission/forms.py
  backend/report_submission/templates/report_submission/step-2.html
  backend/report_submission/templates/report_submission/step-3.html
  backend/report_submission/templates/sidenav.html
  backend/report_submission/test_views.py
  backend/report_submission/urls.py
  backend/report_submission/views.py
  backend/schemas/output/excel/json/additional-eins-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AdditionalEINs.schema.json
  backend/schemas/source/excel/libs/Sheets.libsonnet
  backend/schemas/source/excel/templates/additional-eins-workbook.jsonnet
  backend/schemas/source/sections/AdditionalEINs.schema.jsonnet
  backend/static/js/globals.js
  docs/development.md
Labels: autogenerated, automerge

#1867 2023-08-18 | MAIN --> PROD | DEV (492a7b5) --> STAGING
  .github/pull_request_template.md
  backend/audit/etl.py
  backend/audit/migrations/0035_singleauditchecklist_data_source.py
  backend/audit/models.py
  backend/audit/templates/audit/cross-validation/cross-validation-results.html
  backend/audit/templates/audit/cross-validation/ready-for-certification.html
  backend/audit/test_etl.py
  backend/audit/views.py
  backend/cypress/e2e/audit-info-form.cy.js
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/fixtures/test_workbooks/additional-ueis-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/audit-findings-text-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/corrective-action-plan-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-audit-findings-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/federal-awards-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/notes-to-sefa-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/secondary-auditors-workbook.xlsx
  backend/cypress/support/audit-info-form.js
  backend/cypress/support/auditee-info.js
  backend/cypress/support/cross-validation.js
  backend/cypress/support/workbook-uploads.js
  backend/dissemination/migrations/0026_additionaluei_alter_captext_unique_together_and_more.py
  backend/dissemination/models.py
Labels: autogenerated, automerge

#1894 2023-08-22 | MAIN --> PROD | DEV (2d16f0a) --> STAGING
  .github/PULL_REQUEST_TEMPLATE/pr-review-template.md
  .github/pull_request_template.md
  backend/api/serializers.py
  backend/api/test_serializers.py
  backend/api/test_views.py
  backend/api/views.py
  backend/audit/migrations/0037_access_fullname.py
  backend/audit/models.py
  backend/audit/test_views.py
  backend/audit/views.py
  backend/report_submission/templates/report_submission/step-3.html
  backend/report_submission/test_views.py
  backend/static/js/check-access.js
  backend/static/js/validate.js
  backend/static/scss/_form.scss
  docs/development.md
Labels: autogenerated, automerge

#1895 Bump Cypress action from v5 to v6
  .github/workflows/regression-tests.yml
Labels: infrastructure

#1911 2023-08-23 | MAIN --> PROD | DEV (d3ae270) --> STAGING
  .github/workflows/regression-tests.yml
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/check_award_ref_declaration.py
  backend/audit/cross_validation/check_ref_number_in_cap.py
  backend/audit/cross_validation/check_ref_number_in_findings_text.py
  backend/audit/cross_validation/errors.py
  backend/audit/cross_validation/sac_validation_shape.py
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/cross_validation/test_check_findings_count_consistency.py
  backend/audit/cross_validation/test_check_ref_number_in_cap.py
  backend/audit/cross_validation/test_check_ref_number_in_findings_text.py
  backend/audit/cross_validation/utils.py
  backend/audit/forms.py
  backend/audit/templates/audit/audit-info-form.html
  backend/audit/templates/audit/submission_checklist/submission-checklist.html
  backend/audit/templates/audit/upload-report.html
  backend/audit/test_schemas.py
  backend/audit/test_validators.py
  backend/audit/test_views.py
  backend/audit/viewlib/__init__.py
  backend/audit/viewlib/upload_report_view.py
  backend/audit/views.py
  backend/config/settings.py
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/fixtures/test_workbooks/notes-to-sefa-workbook.xlsx
  backend/cypress/support/auditee-certification.js
  backend/cypress/support/check-access.js
  backend/cypress/support/general-info.js
  backend/cypress/support/workbook-uploads.js
  backend/data_fixtures/audit/excel_schema_test_files/audit-information-pass-01.json
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/report_submission/forms.py
  backend/report_submission/templates/report_submission/gen-form.html
  backend/report_submission/templates/report_submission/upload-page.html
  backend/report_submission/test_views.py
  backend/report_submission/urls.py
  backend/report_submission/views.py
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AuditInformation.schema.json
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/source/sections/AuditInformation.schema.jsonnet
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
  backend/static/js/audit-info-form.js
  backend/static/js/globals.js
  backend/static/scss/_workbook-upload.scss
  backend/static/scss/main.scss
Labels: autogenerated, automerge

#1918 2023-08-24 | MAIN --> PROD | DEV (caf919f) --> STAGING
  backend/Makefile
  backend/audit/templates/audit/audit-info-form.html
  backend/audit/templates/audit/cross-validation/cross-validation-results.html
  backend/audit/templates/audit/cross-validation/cross-validation.html
  backend/audit/templates/audit/cross-validation/ready-for-certification.html
  backend/audit/templates/audit/submission_checklist/submission-checklist.html
  backend/config/settings.py
  backend/config/urls.py
  backend/dev-requirements.txt
  backend/docker-compose-web.yml
  backend/docker-compose.yml
  backend/report_submission/templates/report_submission/step-3.html
  backend/report_submission/templates/report_submission/upload-page.html
  backend/report_submission/views.py
  backend/requirements/dev-requirements.in
  backend/schemas/Makefile
Labels: autogenerated, automerge

#1947 2023-08-25 | MAIN --> PROD | DEV (4d1df3f) --> STAGING
  backend/audit/cross_validation/naming.py
  backend/audit/test_schemas.py
  backend/audit/test_validators.py
  backend/audit/urls.py
  backend/config/settings.py
  backend/data_fixtures/audit/test_data_entries/federal-awards-entries.json
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/report_submission/templates/report_submission/gen-form.html
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/base/ClusterNames.json
  backend/schemas/source/data/cluster-names-20230626.csv
  backend/schemas/source/sections/AuditInformation.schema.jsonnet
  backend/schemas/source/sections/FederalAwards.schema.jsonnet
  backend/schemas/source/sections/SecondaryAuditors.schema.jsonnet
  terraform/shared/modules/env/postgrest.tf
Labels: autogenerated, automerge

#1958 2023-08-28 | MAIN --> PROD | DEV (ec1d92b) --> STAGING
  backend/audit/etl.py
  backend/audit/migrations/0038_singleauditchecklist_cognizant_agency_and_more.py
  backend/audit/models.py
  backend/audit/test_etl.py
  backend/audit/to_rm_tst__cog_agency.py
  backend/dissemination/migrations/0027_additionalein_remove_general_additional_ueis_and_more.py
  backend/dissemination/models.py
Labels: autogenerated, automerge

#1966 2023-08-29 | MAIN --> PROD | DEV (50379b8) --> STAGING
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/excel/libs/Help.libsonnet
  backend/schemas/source/excel/templates/federal-awards-audit-findings-workbook.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.schema.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.validation.libsonnet
Labels: autogenerated, automerge

#1974 2023-08-30 | MAIN --> PROD | DEV (319aba5) --> STAGING
  backend/audit/etl.py
  backend/audit/migrations/0038_singleauditchecklist_cognizant_agency_and_more.py
  backend/audit/models.py
  backend/audit/test_cog_agency.py
  backend/audit/test_etl.py
  backend/dissemination/migrations/0027_additionalein_remove_general_additional_ueis_and_more.py
  backend/dissemination/models.py
  backend/djangooidc/__init__.py
  backend/djangooidc/backends.py
  backend/djangooidc/exceptions.py
  backend/djangooidc/oidc.py
  backend/djangooidc/templates/401.html
  backend/djangooidc/templates/500.html
  backend/djangooidc/tests/__init__.py
  backend/djangooidc/tests/common.py
  backend/djangooidc/tests/test_settings.py
  backend/djangooidc/tests/test_views.py
  backend/djangooidc/urls.py
  backend/djangooidc/views.py
  backend/requirements.txt
  backend/requirements/requirements.in
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/excel/libs/Help.libsonnet
  backend/schemas/source/excel/templates/federal-awards-audit-findings-workbook.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.schema.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.validation.libsonnet
Labels: autogenerated, automerge

#1988 2023-08-31 | MAIN --> PROD | DEV (0d0c126) --> STAGING
  .github/workflows/regression-tests.yml
  backend/audit/cross_validation/naming.py
  backend/audit/cross_validation/sac_validation_shape.py
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/fixtures/single_audit_checklist.py
  backend/audit/management/commands/load_fixtures.py
  backend/audit/templates/audit/upload-report.html
  backend/audit/viewlib/upload_report_view.py
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/fixtures/test_workbooks/additional-eins-workbook.xlsx
  backend/cypress/fixtures/test_workbooks/secondary-auditors-workbook.xlsx
  backend/cypress/support/general-info.js
  backend/cypress/support/logout-gov.js
  backend/cypress/support/workbook-uploads.js
  backend/docker-compose.yml
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/excel/libs/Help.libsonnet
  backend/schemas/source/excel/templates/federal-awards-audit-findings-workbook.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.schema.jsonnet
  backend/schemas/source/sections/FederalAwardsAuditFindings.validation.libsonnet
Labels: autogenerated, automerge
