Repository GSA-TTS/FAC, pull requests merged in 2024-04, with the labels that each got.

#3587 2046: Erroring on biennial + low-risk audits
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/check_biennial_low_risk.py
  backend/audit/cross_validation/errors.py
  backend/audit/cross_validation/test_check_biennial_low_risk.py
Labels: bug

#3598 2024-04-02 | MAIN --> PROD | DEV (958436c) --> STAGING
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/check_biennial_low_risk.py
  backend/audit/cross_validation/errors.py
  backend/audit/cross_validation/test_check_biennial_low_risk.py
  backend/audit/fixtures/single_audit_checklist.py
  backend/audit/forms.py
  backend/audit/templates/audit/auditor-certification-step-1.html
  backend/census_historical_migration/sac_general_lib/auditor_certification.py
  backend/cypress/e2e/full-submission.cy.js
  backend/cypress/support/auditor-certification.js
  backend/cypress/support/dissemination-table.js
  backend/cypress/support/full-submission.js
  backend/cypress/support/initialize-audit.js
  backend/dissemination/api/api_v1_1_0/create_functions.sql
  backend/dissemination/api/api_v1_1_0/create_views.sql
  backend/schemas/output/sections/AuditorCertification.schema.json
  backend/schemas/source/sections/AuditorCertification.schema.jsonnet
  backend/support/api/admin_api_v1_1_0/create_functions.sql
  backend/support/test_admin_api.py
Labels: autogenerated, automerge

#3603 2024-04-03 | MAIN --> PROD | DEV (a5d879a) --> STAGING
  backend/audit/intakelib/checks/check_uei_match.py
  backend/audit/intakelib/checks/check_uei_schema.py
  backend/audit/intakelib/checks/runners.py
  backend/audit/intakelib/common/error_messages.py
  backend/audit/intakelib/mapping_additional_eins.py
  backend/audit/intakelib/mapping_additional_ueis.py
  backend/audit/intakelib/mapping_audit_findings.py
  backend/audit/intakelib/mapping_audit_findings_text.py
  backend/audit/intakelib/mapping_corrective_action_plan.py
  backend/audit/intakelib/mapping_federal_awards.py
  backend/audit/intakelib/mapping_notes_to_sefa.py
  backend/audit/intakelib/mapping_secondary_auditors.py
  backend/audit/test_check_uei_match.py
  backend/audit/test_check_uei_schema.py
  backend/audit/views/views.py
  backend/config/settings.py
  backend/dissemination/templates/advanced.html
  backend/dissemination/templates/search.html
  backend/report_submission/templates/report_submission/upload-page.html
  backend/schemas/Makefile
  backend/schemas/output/base/UeiSchema.json
  backend/schemas/source/base/UeiSchema.jsonnet
  backend/static/js/search-results.js
  backend/static/js/upload-page.js
  docs/local-development.md
Labels: autogenerated, automerge

#3605 2024-04-04 | MAIN --> PROD | DEV (7c7b750) --> STAGING
  .github/workflows/materialize-views.yml
  .github/workflows/materialized-views.yml
  backend/audit/fixtures/workbooks/should_pass/federal_awards/federal-awards-workbook-lots-of-rows.xlsx
  backend/audit/intakelib/checks/check_data_row_range_in_form_sheet.py
  backend/audit/intakelib/checks/runners.py
  backend/audit/intakelib/common/error_messages.py
  backend/audit/test_check_data_row_range.py
  backend/config/settings.py
  backend/schemas/scripts/render.py
Labels: autogenerated, automerge

#3609 2024-04-04 | MAIN --> PROD | DEV (e5b09b5) --> STAGING
  .github/workflows/materialized-views.yml
  backend/dissemination/views.py
Labels: autogenerated, automerge

#3620 2024-04-09 | MAIN --> PROD | DEV (00846cb) --> STAGING
  backend/audit/templates/audit/upload-report.html
  backend/static/js/upload-report-pdf.js
  backend/static/js/upload-report.js
Labels: autogenerated, automerge

#3655 2024-04-12 | MAIN --> PROD | DEV (4de72de) --> STAGING
  backend/package-lock.json
  backend/package.json
Labels: autogenerated, automerge

#3656 2024-04-12 | MAIN --> PROD | DEV (06e3986) --> STAGING
  backend/dissemination/forms.py
  backend/dissemination/search.py
  backend/dissemination/searchlib/search_constants.py
  backend/dissemination/searchlib/search_findings.py
  backend/dissemination/searchlib/search_general.py
  backend/dissemination/searchlib/search_passthrough_name.py
  backend/dissemination/searchlib/search_type_requirement.py
  backend/dissemination/templates/advanced.html
  backend/dissemination/templates/search-alert-info.html
  backend/dissemination/templates/search.html
  backend/dissemination/templates/search_filters/acceptance-date.html
  backend/dissemination/templates/search_filters/aln.html
  backend/dissemination/templates/search_filters/audit-year.html
  backend/dissemination/templates/search_filters/cog-over.html
  backend/dissemination/templates/search_filters/direct_funding.html
  backend/dissemination/templates/search_filters/entity-type.html
  backend/dissemination/templates/search_filters/findings.html
  backend/dissemination/templates/search_filters/fy-end-month.html
  backend/dissemination/templates/search_filters/major-program.html
  backend/dissemination/templates/search_filters/name.html
  backend/dissemination/templates/search_filters/passthrough-name.html
  backend/dissemination/templates/search_filters/report-id.html
  backend/dissemination/templates/search_filters/state.html
  backend/dissemination/templates/search_filters/type-requirement.html
  backend/dissemination/templates/search_filters/uei-ein.html
  backend/dissemination/test_search.py
  backend/dissemination/views.py
  backend/static/js/search-results.js
Labels: autogenerated, automerge

#3663 2024-04-16 | MAIN --> PROD | DEV (c01c93b) --> STAGING
  backend/dissemination/templates/summary.html
Labels: autogenerated, automerge

#3666 2024-04-17 | MAIN --> PROD | DEV (e241e9d) --> STAGING
  backend/census_historical_migration/migrations/0004_elecaudits_multipleueis_elecaudits_uei.py
  backend/census_historical_migration/models.py
  backend/dissemination/summary_reports.py
  backend/dissemination/test_summary_reports.py
Labels: autogenerated, automerge

#3678 2024-04-18 | MAIN --> PROD | DEV (781dca5) --> STAGING
  .github/ISSUE_TEMPLATE/helpdesk-issue.yaml
  .github/workflows/auto-merge-staging-pr.yml
  backend/audit/admin.py
  backend/package-lock.json
  backend/package.json
  backend/requirements.txt
  backend/support/api/admin_api_v1_1_0/create_access_tables.sql
  terraform/meta/config.tf
Labels: autogenerated, automerge

#3683 2024-04-19 | MAIN --> PROD | DEV (82b23c5) --> STAGING
  backend/audit/cross_validation/check_biennial_low_risk.py
  backend/audit/cross_validation/test_check_biennial_low_risk.py
  backend/docker-compose.yml
  backend/templates/includes/nav_primary.html
  docs/development.md
Labels: autogenerated, automerge

#3727 2024-04-20 | MAIN --> PROD | DEV (7698710) --> STAGING
  .github/workflows/trivy.yml
  .github/workflows/zap-scan.yml
  backend/package-lock.json
  backend/package.json
Labels: autogenerated, automerge

#3741 2024-04-23 | MAIN --> PROD | DEV (c59eac9) --> STAGING
  backend/audit/templates/audit/audit-info-form.html
  backend/report_submission/templates/report_submission/gen-form.html
Labels: autogenerated, automerge

#3743 Dependency updates
  backend/package-lock.json
  backend/package.json
Labels: dependencies

#3750 2024-04-24 | MAIN --> PROD | DEV (37b2460) --> STAGING
  .github/workflows/zap-scan.yml
  backend/audit/cross_validation/naming.py
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/migrations/0008_alter_submissionevent_event.py
  backend/audit/models/submission_event.py
  backend/audit/templates/audit/submission_checklist/section_block.html
  backend/audit/views/submission_progress_view.py
  backend/dissemination/templates/search_filters/cog-over.html
  backend/dissemination/templates/search_filters/fy-end-month.html
  backend/package-lock.json
  backend/package.json
  backend/report_submission/templates/report_submission/delete-file-page.html
  backend/report_submission/templates/report_submission/upload-page.html
  backend/report_submission/test_views.py
  backend/report_submission/urls.py
  backend/report_submission/views.py
  backend/requirements/dev-requirements.txt
  backend/requirements/requirements.in
  backend/requirements/requirements.txt
  backend/static/js/search-results.js
Labels: autogenerated, automerge

#3757 2024-04-25 | MAIN --> PROD | DEV (85f283a) --> STAGING
  .github/ISSUE_TEMPLATE/offboarding.md
  backend/audit/cross_validation/submission_progress_check.py
  backend/audit/cross_validation/validate_general_information.py
  backend/audit/fixtures/json/general-information--test0001test--simple-pass.json
  backend/audit/test_utils.py
  backend/audit/utils.py
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/report_submission/views.py
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/GeneralInformationRequired.schema.json
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
  backend/schemas/source/sections/GeneralInformationRequired.schema.jsonnet
Labels: autogenerated, automerge

#3767 2024-04-26 | MAIN --> PROD | DEV (aba8a48) --> STAGING
  backend/audit/cross_validation/__init__.py
  backend/audit/cross_validation/naming.py
  backend/audit/cross_validation/test_check_award_ref_existence.py
  backend/audit/fixtures/excel.py
  backend/audit/management/commands/update_oldformat_reportids.py
  backend/audit/models/access_roles.py
  backend/audit/templatetags/sprite_helper.py
  backend/audit/templatetags/submission_progress_tags.py
  backend/audit/test_intake_to_dissemination.py
  backend/audit/test_validators.py
  backend/audit/test_views.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/workbooklib/findings.py
  backend/config/settings.py
  backend/data_distro/management/commands/handle_errors.py
  backend/data_distro/management/commands/link_data.py
  backend/data_distro/management/commands/process_data.py
  backend/data_distro/management/commands/public_data_loader.py
  backend/data_distro/mappings/upload_mapping.py
  backend/data_distro/migrations/0004_add_new_models.py
  backend/data_distro/migrations/0005_delete_duplicate_fields.py
  backend/data_distro/migrations/0032_update_API.py
  backend/data_distro/migrations/0033_dbkey_to_auditee_API.py
  backend/dev-requirements.txt
  backend/dissemination/templatetags/field_name_to_label.py
  backend/dissemination/templatetags/getkey.py
  backend/dissemination/workbooklib/federal_awards.py
  backend/dissemination/workbooklib/findings.py
  backend/dissemination/workbooklib/sac_creation.py
  backend/requirements/dev-requirements.in
  backend/support/admin.py
Labels: autogenerated, automerge

#3726 3701 address errors caused by bad or missing EINs
  backend/audit/test_schemas.py
  backend/audit/validators.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/test_general_information_xforms.py
  backend/config/settings.py
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/GeneralInformationRequired.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
Labels: census

#3775 2024-04-27 | MAIN --> PROD | DEV (581ca83) --> STAGING
  backend/audit/test_schemas.py
  backend/audit/validators.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/test_general_information_xforms.py
  backend/config/settings.py
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/GeneralInformationRequired.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
Labels: autogenerated, automerge

#3746 Handle Missing entity_type and missing notes for historic audits and track census data
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/test_notes_to_sefa_xforms.py
  backend/census_historical_migration/workbooklib/notes_to_sefa.py
Labels: census

#3753 3695 address historical finding references with invalid formats
  backend/audit/fixtures/workbooks/should_fail/audit-findings/has_bad_finding_reference.xlsx
  backend/audit/intakelib/checks/check_finding_prior_references_pattern.py
  backend/audit/intakelib/checks/check_finding_reference_pattern.py
  backend/audit/intakelib/checks/check_version_number.py
  backend/audit/intakelib/checks/runners.py
  backend/schemas/output/excel/json/additional-eins-workbook.json
  backend/schemas/output/excel/json/additional-ueis-workbook.json
  backend/schemas/output/excel/json/audit-findings-text-workbook.json
  backend/schemas/output/excel/json/corrective-action-plan-workbook.json
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/excel/json/notes-to-sefa-workbook.json
  backend/schemas/output/excel/json/secondary-auditors-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AdditionalEINs.schema.json
  backend/schemas/output/sections/AdditionalUEIs.schema.json
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/output/sections/NotesToSefa.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/excel/libs/SheetValidations.libsonnet
  backend/schemas/source/excel/libs/Sheets.libsonnet
Labels: census

#3779 2024-04-30 | MAIN --> PROD | DEV (1f31913) --> STAGING
  backend/audit/fixtures/workbooks/should_fail/audit-findings/has_bad_finding_reference.xlsx
  backend/audit/intakelib/checks/check_finding_prior_references_pattern.py
  backend/audit/intakelib/checks/check_finding_reference_pattern.py
  backend/audit/intakelib/checks/check_version_number.py
  backend/audit/intakelib/checks/runners.py
  backend/census_historical_migration/sac_general_lib/general_information.py
  backend/census_historical_migration/test_notes_to_sefa_xforms.py
  backend/census_historical_migration/workbooklib/notes_to_sefa.py
  backend/schemas/output/excel/json/additional-eins-workbook.json
  backend/schemas/output/excel/json/additional-ueis-workbook.json
  backend/schemas/output/excel/json/audit-findings-text-workbook.json
  backend/schemas/output/excel/json/corrective-action-plan-workbook.json
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/excel/json/notes-to-sefa-workbook.json
  backend/schemas/output/excel/json/secondary-auditors-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AdditionalEINs.schema.json
  backend/schemas/output/sections/AdditionalUEIs.schema.json
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/output/sections/NotesToSefa.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/excel/libs/SheetValidations.libsonnet
  backend/schemas/source/excel/libs/Sheets.libsonnet
Labels: autogenerated, automerge

#3762 Replacing empty passthrough based on amount
  backend/census_historical_migration/test_federal_awards_xforms.py
  backend/census_historical_migration/workbooklib/federal_awards.py
Labels: census

#3778 Added test cases for xform_missing_notes_records_v2
  backend/census_historical_migration/test_notes_to_sefa_xforms.py
Labels: census
