Repository GSA-TTS/FAC, pull requests merged in 2024-03, with the labels that each got.

#3467 2024-03-01 | MAIN --> PROD | DEV (b14e6e5) --> STAGING
  backend/audit/validators.py
  backend/dissemination/views.py
  backend/support/decorators.py
Labels: autogenerated, automerge

#3470 2024-03-01 | MAIN --> PROD | DEV (2fee193) --> STAGING
  backend/static/js/upload-page.js
Labels: autogenerated, automerge

#3482 2024-03-05 | MAIN --> PROD | DEV (79f56d7) --> STAGING
  .github/workflows/regression-tests.yml
  backend/cypress/support/dissemination-table.js
Labels: autogenerated, automerge

#3487 2024-03-07 | MAIN --> PROD | DEV (c663d6a) --> STAGING
  backend/build-assets.js
  backend/package-lock.json
  backend/package.json
Labels: autogenerated, automerge

#3489 2024-03-08 | MAIN --> PROD | DEV (641b879) --> STAGING
  .github/workflows/trivy.yml
  backend/config/settings.py
  backend/dissemination/search.py
  backend/dissemination/searchlib/search_general.py
  backend/dissemination/summary_reports.py
  backend/dissemination/templates/search.html
  backend/dissemination/templates/summary.html
  backend/dissemination/test_search.py
  backend/dissemination/test_summary_reports.py
  backend/dissemination/test_views.py
  backend/dissemination/views.py
  backend/newrelic.ini
  backend/package-lock.json
  backend/package.json
  backend/requirements/requirements.txt
  backend/tools/setup_cgov_env.sh
Labels: autogenerated, automerge

#3500 2024-03-11 | MAIN --> PROD | DEV (695f045) --> STAGING
  backend/manifests/manifest-fac.yml
Labels: autogenerated, automerge

#3503 2024-03-12 | MAIN --> PROD | DEV (1f9efaf) --> STAGING
  backend/manifests/manifest-fac.yml
Labels: autogenerated, automerge

#3509 2024-03-13 | MAIN --> PROD | DEV (75c994b) --> STAGING
  backend/audit/intakelib/checks/check_version_number.py
  backend/schemas/output/excel/json/additional-eins-workbook.json
  backend/schemas/output/excel/json/additional-ueis-workbook.json
  backend/schemas/output/excel/json/audit-findings-text-workbook.json
  backend/schemas/output/excel/json/corrective-action-plan-workbook.json
  backend/schemas/output/excel/json/federal-awards-audit-findings-workbook.json
  backend/schemas/output/excel/json/federal-awards-workbook.json
  backend/schemas/output/excel/json/notes-to-sefa-workbook.json
  backend/schemas/output/excel/json/secondary-auditors-workbook.json
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/output/sections/AdditionalEINs.schema.json
  backend/schemas/output/sections/AdditionalUEIs.schema.json
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/output/sections/NotesToSefa.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/ClusterNames.json
  backend/schemas/source/data/cluster-names-20230626.csv
  backend/schemas/source/excel/libs/Sheets.libsonnet
  backend/schemas/source/sections/NotesToSefa.schema.jsonnet
Labels: autogenerated, automerge

#3512 Updated Cy test for Unlock Certification v3
  backend/cypress/support/full-submission.js
  backend/cypress/support/unlock-cert.js
Labels: eng

#3520 2024-03-15 | MAIN --> PROD | DEV (ec89a31) --> STAGING
  backend/cypress/support/full-submission.js
  backend/cypress/support/unlock-cert.js
Labels: autogenerated, automerge

#3530 2024-03-18 | MAIN --> PROD | DEV (52d30fb) --> STAGING
  backend/dissemination/templates/search-alert-performance.html
  backend/dissemination/templates/search.html
  backend/dissemination/templates/summary.html
  backend/dissemination/views.py
  backend/static/img/fac-gov-logo.png
  backend/static/img/fac-gov-logo.svg
  backend/static/img/fac-logo-full.svg
  backend/static/img/home/search_for_audits.png
  backend/static/img/home/submit_an_audit.png
  backend/static/scss/_header.scss
  backend/static/scss/_home.scss
  backend/static/scss/_search.scss
  backend/templates/home.html
  backend/templates/includes/header.html
  backend/templates/includes/nav_primary.html
Labels: autogenerated, automerge

#3533 Fix Regression Test Failures Caused by FAC App Update
  backend/cypress/support/login-gov.js
  backend/cypress/support/unlock-cert.js
Labels: eng

#3537 2024-03-20 | MAIN --> PROD | DEV (e2653a1) --> STAGING
  backend/cypress/support/login-gov.js
  backend/cypress/support/unlock-cert.js
  backend/dissemination/views.py
  backend/gunicorn.conf.py
  backend/requirements.txt
  backend/requirements/requirements.in
  backend/schemas/output/excel/xlsx/additional-eins-workbook.xlsx
  backend/schemas/output/excel/xlsx/additional-ueis-workbook.xlsx
  backend/schemas/output/excel/xlsx/audit-findings-text-workbook.xlsx
  backend/schemas/output/excel/xlsx/corrective-action-plan-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-audit-findings-workbook.xlsx
  backend/schemas/output/excel/xlsx/federal-awards-workbook.xlsx
  backend/schemas/output/excel/xlsx/notes-to-sefa-workbook.xlsx
  backend/schemas/output/excel/xlsx/secondary-auditors-workbook.xlsx
  backend/schemas/source/excel/libs/SheetValidations.libsonnet
Labels: autogenerated, automerge

#3562 2024-03-27 | MAIN --> PROD | DEV (ca2456d) --> STAGING
  backend/audit/validators.py
Labels: autogenerated, automerge

#3563 2024-03-27 | MAIN --> PROD | DEV (2dd46d9) --> STAGING
  backend/manifests/vars/vars-production.yml
  terraform/dev/dev.tf
  terraform/production/production.tf
  terraform/shared/modules/env/postgrest.tf
Labels: autogenerated, automerge

#3578 2024-03-28 | MAIN --> PROD | DEV (2663a2b) --> STAGING
  backend/manifests/vars/vars-production.yml
  terraform/production/production.tf
Labels: autogenerated, automerge

#3584 2024-03-29 | MAIN --> PROD | DEV (b890d7d) --> STAGING
  backend/audit/cross_validation/validate_general_information.py
  backend/audit/fixtures/json/general-information--test0001test--simple-pass.json
  backend/audit/test_schemas.py
  backend/audit/test_validators.py
  backend/audit/validators.py
  backend/data_fixtures/audit/test_data_entries/simple-cases.json
  backend/dissemination/templates/summary.html
  backend/dissemination/workbooklib/sac_creation.py
  backend/report_submission/forms.py
  backend/report_submission/test_views.py
  backend/report_submission/views.py
  backend/schemas/output/sections/AdditionalEINs.schema.json
  backend/schemas/output/sections/AdditionalUEIs.schema.json
  backend/schemas/output/sections/AuditFindingsText.schema.json
  backend/schemas/output/sections/CorrectiveActionPlan.schema.json
  backend/schemas/output/sections/FederalAwards.schema.json
  backend/schemas/output/sections/FederalAwardsAuditFindings.schema.json
  backend/schemas/output/sections/GeneralInformation.schema.json
  backend/schemas/output/sections/GeneralInformationComplete.schema.json
  backend/schemas/output/sections/GeneralInformationRequired.schema.json
  backend/schemas/output/sections/NotesToSefa.schema.json
  backend/schemas/output/sections/SecondaryAuditors.schema.json
  backend/schemas/source/base/Base.libsonnet
  backend/schemas/source/sections/GeneralInformation.schema.jsonnet
  backend/schemas/source/sections/GeneralInformationComplete.schema.jsonnet
  backend/schemas/source/sections/GeneralInformationRequired.schema.jsonnet
Labels: autogenerated, automerge

#3586 3160: Removing space from json_array_to_str
  backend/audit/utils.py
Labels: bug

#3588 2024-03-30 | MAIN --> PROD | DEV (f80b140) --> STAGING
  backend/audit/utils.py
Labels: autogenerated, automerge
